<?php 

if($this->checking_both()== 'nothingset')
{
    echo '<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3>' . $this->__('Lexity') .'</h3></td>
            <td class="a-right">
                <button onclick="editForm.submit()" class="scalable save" type="button"><span>Sign in</span></button>
            </td>
        </tr>
    </table>
</div>
   <div class="entry-edit">
    <form id="edit_form" name="edit_form" method="post" action="'.$this->getUrl('*/*/allset').'">
        <input name="form_key" type="hidden" value="'.Mage::getSingleton('core/session')->getFormKey().'" />
        <h4 class="icon-head head-edit-form fieldset-legend">'.$this->__('Account Information').'</h4>
        <fieldset id="my-fieldset">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label">'.$this->__('API Key').'<span class="required">*</span></td>
                    <td class="input-ele"><input class="input-text required-entry" name="myform[api_key]" /></td>
                </tr>
            </table>
        </fieldset>
    </form>
</div><script type="text/javascript">
    var editForm = new varienForm(\'edit_form\');
</script>';
    
}
elseif( ($this->checking_both() == 'miscset') )  // will call userset controller
{
    echo '<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3>' . $this->__('Lexity') .'</h3></td>
            <td class="a-right">
                <button onclick="editForm.submit()" class="scalable save" type="button"><span>Sign in</span></button>
            </td>
        </tr>
    </table>
</div>
   <div class="entry-edit">
    <form id="edit_form" name="edit_form" method="post" action="'.$this->getUrl('*/*/userset').'">
        <input name="form_key" type="hidden" value="'.Mage::getSingleton('core/session')->getFormKey().'" />
        <h4 class="icon-head head-edit-form fieldset-legend">'.$this->__('Account Information').'</h4>
 <ul class="messages"><li class="error-msg"><ul><li>
              <span> Users & Roles not defined </span>
          </li></ul></li></ul>        
<fieldset id="my-fieldset">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label">'.$this->__('API Key').'<span class="required">*</span></td>
                    <td class="input-ele"><input class="input-text required-entry" name="myform[api_key]" /></td>
                </tr>
            </table>
        </fieldset>
    </form>
</div><script type="text/javascript">
    var editForm = new varienForm(\'edit_form\')
</script>';   
}
elseif(($this->checking_both() == 'notmisc')) 
{
    echo '<div class="main-col-inner">
    <div class="content-header"
         <table cellspacing="0">
             <tbody>
                 <tr>
                    <td style="width:50%;"><h3 class="icon-head head-cms-page">Lexity</h3></td>
                        </a></td>
                 </tr>
            </tbody>
        </table>	
    </div>
    <ul class="messages"><li class="error-msg"><ul><li>
              <span> Lexity script not found </span>
          </li></ul></li></ul>'
                . '<button onclick="setLocation(\''.$this->getUrl('*/*/miscset').
					'\')"><span>Fix Problem</span></button>' .
            '
        </form>
        </div>';
    
}
else
    {
     echo '<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3>' . $this->__('Lexity') .'</h3></td>
            <td class="a-right">
                <button onclick="editForm.submit()" class="scalable save" type="button"><span>Update Api</span></button>
            </td>
        </tr>
    </table>
</div>
   <div class="entry-edit">
    <form id="edit_form" name="edit_form" method="post" action="'.$this->getUrl('*/*/apiupdate').'">
        <input name="form_key" type="hidden" value="'.Mage::getSingleton('core/session')->getFormKey().'" />
        <h4 class="icon-head head-edit-form fieldset-legend">'.$this->__('Account Information').'</h4>
        <fieldset id="my-fieldset">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label">'.$this->__('Enter new API Key').'<span class="required">*</span></td>
                    <td class="input-ele"><input class="input-text required-entry" name="myform[api_key]" /></td>
                </tr>
            </table>
        </fieldset>
        </form>
</div><script type="text/javascript">
    var editForm = new varienForm(\'edit_form\');
</script>';

    }
?>



